"""
test_comoving_host.py
~~~~~~~~~~~~~~~~~~~~~
Tests for the comoving-host helpers in ``agama_helper._fire``: the
principal-axis rotation, the centre-of-mass splines, and the galactic-centre
acceleration correction.

The centre term ``u_dot = a x_com'' + H a x_com'`` is the one piece of the
comoving equation of motion that does **not** cancel when changing variables to
physical coordinates, so it is worth pinning down exactly.

Covers
------
1. ``read_rotation`` takes the last three uncommented rows, with and without
   the ``# rotation to principal-axis frame`` comment that only half the FIRE
   suite writes.
2. ``write_center_splines`` / ``read_center_splines`` round-trip a BSpline
   exactly, including its derivatives -- the text form is what the acceleration
   is built from.
3. The acceleration table reproduces the closed-form ``-u_dot`` row by row,
   including the ``/K^2`` unit conversion that is wrong by 9.4 percent if
   multiplied instead.
4. Rotation, path-pattern input, ``t_range`` and ``n_samples`` behaviour.
5. ``center_acceleration`` and ``write_center_acceleration`` produce identical
   forces through agama, through the written ``.ini``, and (when CuPy is
   present) through ``PotentialGPU``.
"""

import numpy as np
import pytest

from nbody_streams.agama_helper import (
    center_acceleration,
    center_acceleration_table,
    read_center_splines,
    read_rotation,
    write_center_acceleration,
    write_center_splines,
)
from nbody_streams.utils import KPC_PER_GYR_PER_KMS, FlatLCDM

agama = pytest.importorskip("agama")
make_interp_spline = pytest.importorskip("scipy.interpolate").make_interp_spline

COSMO = FlatLCDM()
T_LO, T_HI = 1.0, 13.7


@pytest.fixture(scope="module")
def splines():
    """Three smooth, non-degenerate centre tracks, quintic like FIRE's."""
    t = np.linspace(T_LO, T_HI, 60)
    return [make_interp_spline(t, 30.0 * np.sin(0.4 * t + k) + 2.0 * t, k=5)
            for k in range(3)]


@pytest.fixture(scope="module")
def rotation():
    return np.linalg.qr(np.random.default_rng(1).normal(size=(3, 3)))[0]


# ---------------------------------------------------------------------------
# read_rotation
# ---------------------------------------------------------------------------

def _write_coords(sim_dir, rot, nsnap=600, comment=True, spl=True):
    pot = sim_dir / "potential" / "10kpc"
    pot.mkdir(parents=True, exist_ok=True)
    body = "\n".join(" ".join(f"{v:.17g}" for v in row) for row in rot)
    head = "# generated by the FIRE pipeline\n1 2 3 4\n5 6 7 8\n"
    if comment:
        head += "# rotation to principal-axis frame\n"
    suffix = "_coords_spl.txt" if spl else "_coords.txt"
    (pot / f"{nsnap}{suffix}").write_text(head + body + "\n")
    return sim_dir


@pytest.mark.parametrize("comment", [True, False])
def test_read_rotation_ignores_the_optional_comment(tmp_path, rotation, comment):
    """m12m/m12f label the block; m12i/m12b do not. Both must work."""
    sim = _write_coords(tmp_path, rotation, comment=comment)
    assert np.allclose(read_rotation(sim, nsnap=600), rotation)


def test_read_rotation_spl_flag_picks_the_other_file(tmp_path, rotation):
    sim = _write_coords(tmp_path, rotation, spl=False)
    assert np.allclose(read_rotation(sim, nsnap=600, spl=False), rotation)
    with pytest.raises(FileNotFoundError):
        read_rotation(sim, nsnap=600, spl=True)


def test_read_rotation_rejects_a_short_file(tmp_path):
    pot = tmp_path / "potential" / "10kpc"
    pot.mkdir(parents=True)
    (pot / "600_coords_spl.txt").write_text("# only a comment\n1 2 3\n")
    with pytest.raises(ValueError, match="last three"):
        read_rotation(tmp_path, nsnap=600)


# ---------------------------------------------------------------------------
# Centre splines
# ---------------------------------------------------------------------------

def test_center_spline_text_round_trip_is_exact(tmp_path, splines):
    """The .txt form must rebuild the same BSpline, derivatives included."""
    pattern = str(tmp_path / "cen_{}.txt")
    written = write_center_splines(pattern, splines)
    assert [p.rsplit("_", 1)[1] for p in written] == ["x.txt", "y.txt", "z.txt"]

    back = read_center_splines(pattern)
    tq = np.linspace(T_LO + 0.5, T_HI - 0.5, 97)
    for orig, new in zip(splines, back):
        assert new.k == orig.k
        assert np.array_equal(new.t, orig.t)
        assert np.array_equal(new(tq), orig(tq))
        assert np.array_equal(new.derivative(2)(tq), orig.derivative(2)(tq))


def test_write_center_splines_rejects_wrong_count(tmp_path, splines):
    with pytest.raises(ValueError, match="expected 3"):
        write_center_splines(str(tmp_path / "cen_{}.txt"), splines[:2])


def test_read_center_splines_reports_missing_and_headerless(tmp_path, splines):
    with pytest.raises(FileNotFoundError):
        read_center_splines(str(tmp_path / "absent_{}.txt"))
    for c in "xyz":
        (tmp_path / f"bad_{c}.txt").write_text("1 2\n3 4\n")
    with pytest.raises(ValueError, match="degree"):
        read_center_splines(str(tmp_path / "bad_{}.txt"))


# ---------------------------------------------------------------------------
# Centre acceleration table
# ---------------------------------------------------------------------------

def test_table_matches_the_closed_form(splines, rotation):
    """-u_dot = -(a x'' / K^2 + a H x' / K) R^T, row by row."""
    tab = center_acceleration_table(splines, rotation, COSMO, n_samples=401)
    assert tab.shape == (401, 4)

    t = tab[:, 0]
    a = COSMO.scale_factor(t)
    H = COSMO.hubble_parameter(a=a)
    d1 = np.column_stack([sp.derivative(1)(t) for sp in splines])
    d2 = np.column_stack([sp.derivative(2)(t) for sp in splines])
    K = KPC_PER_GYR_PER_KMS
    ref = -((a[:, None] * d2 / K ** 2 + (a * H)[:, None] * d1 / K) @ rotation.T)
    assert np.allclose(tab[:, 1:], ref, rtol=0, atol=1e-14)


def test_unit_conversion_divides_by_k_squared():
    """A hand-computable case, in the static background where a = 1 and H = 0.

    Only the ``x_com''/K^2`` term survives, so a centre track with a known
    constant acceleration in kpc/Gyr^2 pins the conversion exactly.  Multiplying
    by ``K^2`` instead is wrong by 9.4 percent -- plausible enough to go
    unnoticed, large enough to matter.
    """
    accel = 3.0                                    # kpc/Gyr^2, x component only
    t = np.linspace(1.0, 13.0, 40)
    sp = [make_interp_spline(t, 0.5 * accel * t ** 2, k=3),
          make_interp_spline(t, np.zeros_like(t), k=3),
          make_interp_spline(t, np.zeros_like(t), k=3)]

    tab = center_acceleration_table(sp, np.eye(3), FlatLCDM.static(), n_samples=101)
    expected = -accel / KPC_PER_GYR_PER_KMS ** 2   # (km/s)^2/kpc
    assert np.allclose(tab[:, 1], expected, rtol=1e-9)
    assert np.allclose(tab[:, 2:], 0.0, atol=1e-9)
    # The wrong sense of the conversion would sit 9.4 percent away.
    assert abs(expected * KPC_PER_GYR_PER_KMS ** 4 / expected - 1.0) > 0.09


def test_hubble_term_scales_with_a_h():
    """With a straight-line centre track x'' = 0, only ``a H x'/K`` is left."""
    speed = 5.0                                     # kpc/Gyr, x component only
    t = np.linspace(1.0, 13.0, 40)
    sp = [make_interp_spline(t, speed * t, k=3),
          make_interp_spline(t, np.zeros_like(t), k=3),
          make_interp_spline(t, np.zeros_like(t), k=3)]

    tab = center_acceleration_table(sp, np.eye(3), COSMO, n_samples=101)
    a = COSMO.scale_factor(tab[:, 0])
    H = COSMO.hubble_parameter(a=a)
    assert np.allclose(tab[:, 1], -a * H * speed / KPC_PER_GYR_PER_KMS, rtol=1e-9)


def test_table_honours_rotation(splines):
    """The identity rotation leaves the components in the simulation frame."""
    eye = center_acceleration_table(splines, np.eye(3), COSMO, n_samples=101)
    rot = np.linalg.qr(np.random.default_rng(7).normal(size=(3, 3)))[0]
    got = center_acceleration_table(splines, rot, COSMO, n_samples=101)
    assert np.allclose(got[:, 1:], eye[:, 1:] @ rot.T)


def test_table_accepts_a_path_pattern(tmp_path, splines, rotation):
    pattern = str(tmp_path / "cen_{}.txt")
    write_center_splines(pattern, splines)
    from_pattern = center_acceleration_table(pattern, rotation, COSMO, n_samples=201)
    from_objects = center_acceleration_table(splines, rotation, COSMO, n_samples=201)
    assert np.allclose(from_pattern, from_objects)


def test_default_t_range_is_the_knot_range(splines, rotation):
    tab = center_acceleration_table(splines, rotation, COSMO)
    assert tab.shape == (1201, 4)
    assert tab[0, 0] == pytest.approx(T_LO)
    assert tab[-1, 0] == pytest.approx(T_HI)


def test_t_range_is_not_clipped_to_the_knots(splines, rotation):
    """FIRE centre splines stop 4.4 Myr short of snapshot 600; the table must
    still be allowed to reach the present day by extrapolation."""
    tab = center_acceleration_table(splines, rotation, COSMO,
                                    t_range=(T_LO, T_HI + 0.05), n_samples=101)
    assert tab[-1, 0] == pytest.approx(T_HI + 0.05)
    assert np.all(np.isfinite(tab))


def test_table_validation(splines, rotation):
    with pytest.raises(ValueError, match=r"\(3, 3\)"):
        center_acceleration_table(splines, np.eye(2), COSMO)
    with pytest.raises(ValueError, match="empty"):
        center_acceleration_table(splines, rotation, COSMO, t_range=(5.0, 5.0))
    with pytest.raises(ValueError, match="n_samples"):
        center_acceleration_table(splines, rotation, COSMO, n_samples=1)


# ---------------------------------------------------------------------------
# Potential construction
# ---------------------------------------------------------------------------

def test_center_acceleration_force_matches_the_table(splines, rotation):
    """UniformAcceleration force is +a(t), independent of position."""
    tab = center_acceleration_table(splines, rotation, COSMO, n_samples=401)
    pot = center_acceleration(splines, rotation, COSMO, n_samples=401)

    xyz = np.array([[8.0, 1.0, -2.0], [50.0, -30.0, 10.0], [0.0, 0.0, 0.0]])
    i = 200
    force = np.atleast_2d(pot.force(xyz, t=tab[i, 0]))
    assert np.allclose(force, tab[i, 1:], rtol=1e-10, atol=1e-12)
    assert np.allclose(force[0], force[-1])          # spatially uniform


def test_written_table_and_ini_reproduce_the_potential(tmp_path, splines, rotation):
    path = tmp_path / "accCEN.txt"
    written = write_center_acceleration(path, splines, rotation, COSMO, n_samples=401)
    assert written == str(path)

    ini = path.with_suffix(".ini")
    assert "UniformAcceleration" in ini.read_text()

    direct = center_acceleration(splines, rotation, COSMO, n_samples=401)
    from_ini = agama.Potential(str(ini))
    from_file = agama.Potential(type="UniformAcceleration", file=str(path))

    xyz = np.array([[8.0, 1.0, -2.0], [50.0, -30.0, 10.0]])
    for t in (2.0, 7.0, 13.0):
        ref = np.atleast_2d(direct.force(xyz, t=t))
        assert np.allclose(np.atleast_2d(from_ini.force(xyz, t=t)), ref)
        assert np.allclose(np.atleast_2d(from_file.force(xyz, t=t)), ref)


def test_write_center_acceleration_can_skip_the_ini(tmp_path, splines, rotation):
    path = tmp_path / "accCEN.txt"
    write_center_acceleration(path, splines, rotation, COSMO, n_samples=51, ini=False)
    assert path.exists()
    assert not path.with_suffix(".ini").exists()


def test_gpu_matches_cpu(splines, rotation):
    """Both sides use Agama's regularized natural cubic spline on the table."""
    cp = pytest.importorskip("cupy")

    cpu = center_acceleration(splines, rotation, COSMO, n_samples=401)
    gpu = center_acceleration(splines, rotation, COSMO, n_samples=401, gpu=True)

    xyz = np.array([[8.0, 1.0, -2.0], [50.0, -30.0, 10.0]])
    for t in (2.0, 7.0, 13.0):
        got = np.atleast_2d(cp.asnumpy(gpu.force(xyz, t=t)))
        assert np.allclose(got, np.atleast_2d(cpu.force(xyz, t=t)), rtol=1e-12, atol=1e-14)


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
